name: Test Podman Installer

on:
  push:
    branches: [ main, f/add-podman ]
  pull_request:
    branches: [ main, f/add-podman ]

jobs:
  ubuntu-test:
    name: Ubuntu 22.04
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clean up existing Podman
        run: |
          sudo apt-get remove -y podman || true
          sudo rm -rf /var/lib/containers /var/lib/cni /var/lib/podman || true
          sudo rm -rf ~/.local/share/containers || true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl git uidmap slirp4netns fuse-overlayfs dbus-user-session

      - name: Configure rootless
        run: |
          # Add user to subuid and subgid
          echo "$USER:100000:65536" | sudo tee -a /etc/subuid
          echo "$USER:100000:65536" | sudo tee -a /etc/subgid
          # Ensure proper permissions
          sudo chmod 644 /etc/subuid /etc/subgid
          # Configure user namespace
          echo "user.max_user_namespaces=28633" | sudo tee -a /etc/sysctl.conf
          sudo sysctl -p
          # Set up user namespace
          sudo sysctl -w kernel.unprivileged_userns_clone=1
          # Create necessary directories
          mkdir -p ~/.config/containers
          # Configure storage
          cat > ~/.config/containers/storage.conf << EOF
          [storage]
          driver = "overlay"
          runroot = "/run/user/$(id -u)/containers"
          graphroot = "~/.local/share/containers/storage"
          [storage.options]
          mount_program = "/usr/bin/fuse-overlayfs"
          EOF
          # Set environment variables
          echo 'export XDG_RUNTIME_DIR="/run/user/$(id -u)"' >> ~/.bashrc
          echo 'export CONTAINERS_STORAGE_CONF="~/.config/containers/storage.conf"' >> ~/.bashrc
          source ~/.bashrc

      - name: Run Podman Installer
        run: |
          chmod +x devsecops/install_podman.sh
          # Disable interactive prompts
          export PODMAN_SKIP_PROMPTS=1
          # Run with debug output
          bash -x ./devsecops/install_podman.sh

      - name: Validate Podman rootless mode
        run: |
          if podman info | grep -q "rootless: true"; then
            echo "✅ Rootless mode confirmed"
          else
            echo "❌ Rootless mode NOT enabled"
            podman info || true
            exit 1
          fi

  debian-test:
    name: Debian 12
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    container:
      image: debian:12
      options: --privileged --security-opt seccomp=unconfined

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clean up existing Podman
        run: |
          apt-get remove -y podman || true
          rm -rf /var/lib/containers /var/lib/cni /var/lib/podman || true
          rm -rf ~/.local/share/containers || true

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y sudo curl git uidmap slirp4netns fuse-overlayfs dbus-user-session procps

      - name: Configure rootless
        run: |
          # Add user to subuid and subgid
          echo "$USER:100000:65536" | sudo tee -a /etc/subuid
          echo "$USER:100000:65536" | sudo tee -a /etc/subgid
          # Ensure proper permissions
          chmod 644 /etc/subuid /etc/subgid
          # Configure user namespace
          echo "user.max_user_namespaces=28633" | sudo tee -a /etc/sysctl.conf
          sudo sysctl -p
          # Set up user namespace
          sudo sysctl -w kernel.unprivileged_userns_clone=1
          # Create necessary directories
          mkdir -p ~/.config/containers
          # Configure storage
          cat > ~/.config/containers/storage.conf << EOF
          [storage]
          driver = "overlay"
          runroot = "/run/user/$(id -u)/containers"
          graphroot = "~/.local/share/containers/storage"
          [storage.options]
          mount_program = "/usr/bin/fuse-overlayfs"
          EOF
          # Set environment variables
          echo 'export XDG_RUNTIME_DIR="/run/user/$(id -u)"' >> ~/.bashrc
          echo 'export CONTAINERS_STORAGE_CONF="~/.config/containers/storage.conf"' >> ~/.bashrc
          . ~/.bashrc
          # Ensure proper permissions for runtime directory
          mkdir -p /run/user/$(id -u)
          chmod 700 /run/user/$(id -u)
          # Configure Podman for rootless
          mkdir -p ~/.config/containers
          cat > ~/.config/containers/containers.conf << EOF
          [containers]
          netns="slirp4netns"
          [engine]
          cgroup_manager = "cgroupfs"
          events_logger = "file"
          EOF

      - name: Run Podman Installer
        run: |
          chmod +x devsecops/install_podman.sh
          # Disable interactive prompts
          export PODMAN_SKIP_PROMPTS=1
          # Run with debug output
          bash -x ./devsecops/install_podman.sh

      - name: Validate Podman rootless mode
        run: |
          if podman info | grep -q "rootless: true"; then
            echo "✅ Rootless mode confirmed"
          else
            echo "❌ Rootless mode NOT enabled"
            podman info || true
            exit 1
          fi

  fedora-test:
    name: Fedora 39
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    container:
      image: fedora:39
      options: --privileged --security-opt seccomp=unconfined

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clean up existing Podman
        run: |
          dnf remove -y podman || true
          rm -rf /var/lib/containers /var/lib/cni /var/lib/podman || true
          rm -rf ~/.local/share/containers || true

      - name: Install dependencies
        run: |
          dnf update -y
          dnf install -y sudo curl git shadow-utils slirp4netns fuse-overlayfs dbus-daemon procps-ng

      - name: Configure rootless
        run: |
          # Add user to subuid and subgid
          echo "$USER:100000:65536" | sudo tee -a /etc/subuid
          echo "$USER:100000:65536" | sudo tee -a /etc/subgid
          # Ensure proper permissions
          chmod 644 /etc/subuid /etc/subgid
          # Configure user namespace
          echo "user.max_user_namespaces=28633" | sudo tee -a /etc/sysctl.conf
          sudo sysctl -p
          # Set up user namespace
          sudo sysctl -w kernel.unprivileged_userns_clone=1
          # Create necessary directories
          mkdir -p ~/.config/containers
          # Configure storage
          cat > ~/.config/containers/storage.conf << EOF
          [storage]
          driver = "overlay"
          runroot = "/run/user/$(id -u)/containers"
          graphroot = "~/.local/share/containers/storage"
          [storage.options]
          mount_program = "/usr/bin/fuse-overlayfs"
          EOF
          # Set environment variables
          echo 'export XDG_RUNTIME_DIR="/run/user/$(id -u)"' >> ~/.bashrc
          echo 'export CONTAINERS_STORAGE_CONF="~/.config/containers/storage.conf"' >> ~/.bashrc
          source ~/.bashrc

      - name: Run Podman Installer
        run: |
          chmod +x devsecops/install_podman.sh
          # Disable interactive prompts
          export PODMAN_SKIP_PROMPTS=1
          # Run with debug output
          bash -x ./devsecops/install_podman.sh

      - name: Validate Podman rootless mode
        run: |
          if podman info | grep -q "rootless: true"; then
            echo "✅ Rootless mode confirmed"
          else
            echo "❌ Rootless mode NOT enabled"
            podman info || true
            exit 1
          fi
