name: Test Podman Installer

on:
  push:
    branches: [ main, f/add-podman ]
  pull_request:
    branches: [ main, f/add-podman ]

jobs:
  ubuntu-test:
    name: Ubuntu 22.04
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl git uidmap slirp4netns fuse-overlayfs dbus-user-session

      - name: Configure rootless
        run: |
          # Add user to subuid and subgid
          echo "$USER:100000:65536" | sudo tee -a /etc/subuid
          echo "$USER:100000:65536" | sudo tee -a /etc/subgid

      - name: Run Podman Installer
        run: |
          chmod +x devsecops/install_podman.sh
          # Disable interactive prompts
          export PODMAN_SKIP_PROMPTS=1
          # Run with debug output
          bash -x ./devsecops/install_podman.sh

      - name: Validate Podman rootless mode
        run: |
          if podman info | grep -q "rootless: true"; then
            echo "✅ Rootless mode confirmed"
          else
            echo "❌ Rootless mode NOT enabled"
            podman info || true
            exit 1
          fi

  debian-test:
    name: Debian 12
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    container:
      image: debian:12
      options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y sudo curl git uidmap slirp4netns fuse-overlayfs dbus-user-session

      - name: Configure rootless
        run: |
          # Add user to subuid and subgid
          echo "$USER:100000:65536" | sudo tee -a /etc/subuid
          echo "$USER:100000:65536" | sudo tee -a /etc/subgid

      - name: Run Podman Installer
        run: |
          chmod +x devsecops/install_podman.sh
          # Disable interactive prompts
          export PODMAN_SKIP_PROMPTS=1
          # Run with debug output
          bash -x ./devsecops/install_podman.sh

      - name: Validate Podman rootless mode
        run: |
          if podman info | grep -q "rootless: true"; then
            echo "✅ Rootless mode confirmed"
          else
            echo "❌ Rootless mode NOT enabled"
            podman info || true
            exit 1
          fi

  fedora-test:
    name: Fedora 39
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    container:
      image: fedora:39
      options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          dnf update -y
          dnf install -y sudo curl git shadow-utils slirp4netns fuse-overlayfs dbus-user-session

      - name: Configure rootless
        run: |
          # Add user to subuid and subgid
          echo "$USER:100000:65536" | sudo tee -a /etc/subuid
          echo "$USER:100000:65536" | sudo tee -a /etc/subgid

      - name: Run Podman Installer
        run: |
          chmod +x devsecops/install_podman.sh
          # Disable interactive prompts
          export PODMAN_SKIP_PROMPTS=1
          # Run with debug output
          bash -x ./devsecops/install_podman.sh

      - name: Validate Podman rootless mode
        run: |
          if podman info | grep -q "rootless: true"; then
            echo "✅ Rootless mode confirmed"
          else
            echo "❌ Rootless mode NOT enabled"
            podman info || true
            exit 1
          fi
