name: Test Podman Installer

on:
  push:
    paths:
      - "devsecops/install_podman.sh"
  pull_request:
    paths:
      - "devsecops/install_podman.sh"

jobs:
  ubuntu-tests:
    name: Ubuntu ${{ matrix.version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["20.04", "22.04"]
      fail-fast: false

    container:
      image: ubuntu:${{ matrix.version }}
      options: --privileged

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y sudo curl git

      - name: Run Podman Installer
        run: |
          chmod +x devsecops/install_podman.sh
          ./devsecops/install_podman.sh

      - name: Validate Podman rootless mode
        run: |
          if podman info | grep -q "rootless: true"; then
            echo "✅ Rootless mode confirmed"
          else
            echo "❌ Rootless mode NOT enabled"
            podman info || true
            exit 1
          fi

  debian-tests:
    name: Debian ${{ matrix.version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["11", "12"]
      fail-fast: false

    container:
      image: debian:${{ matrix.version }}
      options: --privileged

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y sudo curl git

      - name: Run Podman Installer
        run: |
          chmod +x devsecops/install_podman.sh
          ./devsecops/install_podman.sh

      - name: Validate Podman rootless mode
        run: |
          if podman info | grep -q "rootless: true"; then
            echo "✅ Rootless mode confirmed"
          else
            echo "❌ Rootless mode NOT enabled"
            podman info || true
            exit 1
          fi

  fedora-tests:
    name: Fedora ${{ matrix.version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["38", "39"]
      fail-fast: false

    container:
      image: fedora:${{ matrix.version }}
      options: --privileged

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          dnf update -y
          dnf install -y sudo curl git

      - name: Run Podman Installer
        run: |
          chmod +x devsecops/install_podman.sh
          ./devsecops/install_podman.sh

      - name: Validate Podman rootless mode
        run: |
          if podman info | grep -q "rootless: true"; then
            echo "✅ Rootless mode confirmed"
          else
            echo "❌ Rootless mode NOT enabled"
            podman info || true
            exit 1
          fi

  centos-tests:
    name: CentOS ${{ matrix.version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["8", "9"]
      fail-fast: false

    container:
      image: quay.io/centos/centos:stream${{ matrix.version }}
      options: --privileged

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          yum update -y
          yum install -y sudo curl git

      - name: Run Podman Installer
        run: |
          chmod +x devsecops/install_podman.sh
          ./devsecops/install_podman.sh

      - name: Validate Podman rootless mode
        run: |
          if podman info | grep -q "rootless: true"; then
            echo "✅ Rootless mode confirmed"
          else
            echo "❌ Rootless mode NOT enabled"
            podman info || true
            exit 1
          fi

  macos-test:
    name: macOS
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Run Podman Installer
        run: |
          chmod +x devsecops/install_podman.sh
          ./devsecops/install_podman.sh

      - name: Validate Podman rootless mode
        run: |
          if podman info | grep -q "rootless: true"; then
            echo "✅ Rootless mode confirmed"
          else
            echo "❌ Rootless mode NOT enabled"
            podman info || true
            exit 1
          fi

  windows-test:
    name: Windows (Git Bash)
    runs-on: windows-latest
    shell: bash

    steps:
      - uses: actions/checkout@v4

      - name: Run Podman Installer
        run: |
          chmod +x devsecops/install_podman.sh
          ./devsecops/install_podman.sh

      - name: Validate Podman rootless mode
        run: |
          if podman info | grep -q "rootless: true"; then
            echo "✅ Rootless mode confirmed"
          else
            echo "❌ Rootless mode NOT enabled"
            podman info || true
            exit 1
          fi
