name: Test Basic

on:
  push:
    branches: [ main, f/add-podman ]
  pull_request:
    branches: [ main, f/add-podman ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo "Hello World"
